services:
  app:
    container_name: cloudmirror-dev
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - ./credentials.json:/app/credentials.json:ro
      - gobin:/go/bin
      - gomodcache:/go/pkg/mod
volumes:
  gomodcache:
  gobin:
