services:
  app:
    container_name: cloudmirror-dev
    build: .
    working_dir: /app
    volumes:
      - ./:/app
      - gobin:/go/bin
      - gomodcache:/go/pkg/mod
    command: tail -f /dev/null
volumes:
  gomodcache:
  gobin:
